# Generated by Django 5.2.4 on 2025-07-23 08:29

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AnalysisResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField(max_length=255, verbose_name='파일명')),
                ('file_size', models.IntegerField(verbose_name='파일 크기')),
                ('file_type', models.CharField(max_length=50, verbose_name='파일 타입')),
                ('is_phishing', models.BooleanField(verbose_name='보이스피싱 여부')),
                ('confidence', models.FloatField(verbose_name='신뢰도')),
                ('phishing_type', models.CharField(blank=True, max_length=50, null=True, verbose_name='피싱 유형')),
                ('stt_text', models.TextField(blank=True, null=True, verbose_name='STT 변환 텍스트')),
                ('risk_factors', models.JSONField(default=list, verbose_name='위험 요소')),
                ('explanation', models.TextField(blank=True, null=True, verbose_name='분석 설명')),
                ('warning_message', models.TextField(blank=True, null=True, verbose_name='경고 메시지')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='생성일시')),
                ('processing_time', models.FloatField(blank=True, null=True, verbose_name='처리 시간(초)')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP 주소')),
            ],
            options={
                'verbose_name': '분석 결과',
                'verbose_name_plural': '분석 결과들',
                'db_table': 'voice_phishing_results',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SystemLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(choices=[('INFO', 'Info'), ('WARNING', 'Warning'), ('ERROR', 'Error'), ('CRITICAL', 'Critical')], max_length=10, verbose_name='로그 레벨')),
                ('message', models.TextField(verbose_name='메시지')),
                ('file_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='관련 파일')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP 주소')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='생성일시')),
            ],
            options={
                'verbose_name': '시스템 로그',
                'verbose_name_plural': '시스템 로그들',
                'db_table': 'system_logs',
                'ordering': ['-created_at'],
            },
        ),
    ]
