# Generated by Django 5.2.4 on 2025-07-23 16:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('woogawooga', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModelRegistry',
            fields=[
                ('mdl_id', models.CharField(max_length=20, primary_key=True, serialize=False, verbose_name='모델ID')),
                ('mdl_nm', models.CharField(max_length=100, verbose_name='모델명')),
                ('use_yn', models.CharField(max_length=1, verbose_name='사용여부')),
            ],
            options={
                'verbose_name': '모델 레지스트리',
                'verbose_name_plural': '모델 레지스트리들',
                'db_table': 'ModelRegistry',
            },
        ),
        migrations.CreateModel(
            name='ProcessdFile',
            fields=[
                ('ocrn_no', models.CharField(max_length=50, primary_key=True, serialize=False, verbose_name='발생번호')),
                ('ocrn_hm', models.DateTimeField(verbose_name='발생시분')),
                ('trsc_file_nm', models.CharField(blank=True, max_length=300, null=True, verbose_name='전사파일명')),
                ('transcript', models.TextField(verbose_name='전사내용')),
                ('prcs_cont_1', models.JSONField(verbose_name='1차 전처리내용')),
                ('prcs_cont_2', models.JSONField(blank=True, null=True, verbose_name='2차 전처리내용')),
                ('vldtn_yn', models.CharField(max_length=1, verbose_name='유효성 여부')),
                ('stats_file_path', models.CharField(max_length=200, verbose_name='통계파일경로')),
                ('file_path', models.CharField(max_length=200, verbose_name='파일경로')),
            ],
            options={
                'verbose_name': '처리된 파일',
                'verbose_name_plural': '처리된 파일들',
                'db_table': 'ProcessdFile',
            },
        ),
        migrations.AlterModelOptions(
            name='systemlog',
            options={'ordering': ['-created_at'], 'verbose_name': '기존 시스템 로그', 'verbose_name_plural': '기존 시스템 로그들'},
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prp_no', models.CharField(max_length=20, verbose_name='제안번호')),
                ('rslt_id', models.CharField(max_length=50, verbose_name='결과ID')),
                ('ocrn_no', models.CharField(max_length=50, verbose_name='발생번호')),
                ('prdt_rslt_yn', models.CharField(max_length=1, verbose_name='예측결과여부')),
                ('wropn_cn', models.TextField(blank=True, null=True, verbose_name='의견내용')),
                ('opnn_reg_ymd', models.DateTimeField(blank=True, null=True, verbose_name='의견등록일시')),
            ],
            options={
                'verbose_name': '피드백',
                'verbose_name_plural': '피드백들',
                'db_table': 'feedback',
                'unique_together': {('prp_no', 'rslt_id', 'ocrn_no')},
            },
        ),
        migrations.CreateModel(
            name='InferenceResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rslt_id', models.CharField(max_length=50, verbose_name='결과ID')),
                ('mdl_id', models.CharField(max_length=20, verbose_name='모델ID')),
                ('file_id', models.CharField(max_length=20, verbose_name='파일ID')),
                ('prdt_scr', models.DecimalField(decimal_places=3, max_digits=4, verbose_name='예측점수')),
                ('ml_rslt_cd', models.CharField(choices=[('0', '정상'), ('1', '피싱'), ('보류', '보류')], max_length=10, verbose_name='ML결과코드')),
                ('dl_jdgm_yn', models.CharField(blank=True, max_length=1, null=True, verbose_name='DL판단여부')),
                ('phsh_tp_nm', models.CharField(max_length=100, verbose_name='피싱유형명')),
                ('warn_cn', models.TextField(verbose_name='경고내용')),
                ('prdt_dt', models.DateTimeField(verbose_name='예측일시')),
                ('ocrn_no', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='woogawooga.processdfile', verbose_name='발생번호')),
            ],
            options={
                'verbose_name': '추론 결과',
                'verbose_name_plural': '추론 결과들',
                'db_table': 'InferenceResult',
                'unique_together': {('rslt_id', 'ocrn_no')},
            },
        ),
        migrations.CreateModel(
            name='VoicePhishingSystemLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('log_nm', models.CharField(max_length=300, verbose_name='로그명')),
                ('err_no', models.CharField(blank=True, max_length=20, null=True, verbose_name='에러번호')),
                ('log_reg_dt', models.DateTimeField(verbose_name='로그등록일시')),
                ('log_ocrn_pstn', models.CharField(max_length=200, verbose_name='로그발생위치')),
                ('err_rsn', models.TextField(blank=True, null=True, verbose_name='에러사유')),
                ('err_cd_nm', models.CharField(blank=True, max_length=300, null=True, verbose_name='에러코드명')),
                ('ocrn_no', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='woogawooga.processdfile', verbose_name='발생번호')),
            ],
            options={
                'verbose_name': '시스템 로그',
                'verbose_name_plural': '시스템 로그들',
                'db_table': 'SystemLog',
                'unique_together': {('log_nm', 'ocrn_no')},
            },
        ),
    ]
