# Generated by Claude Code
from django.db import migrations
from pathlib import Path

def populate_model_registry(apps, schema_editor):
    """ModelRegistry에 models 폴더의 모든 모델 등록"""
    ModelRegistry = apps.get_model('woogawooga', 'ModelRegistry')
    
    # 등록할 모델 정보
    models_data = [
        # 1차 머신러닝 모델들 (pickle 기반)
        {
            'mdl_id': 'STACK_V1',
            'mdl_nm': 'Stacking 앙상블 모델 v1 (1차)',
            'use_yn': 'N'
        },
        {
            'mdl_id': 'STACK_V2',
            'mdl_nm': 'Stacking 앙상블 모델 v2 (1차 주력)',
            'use_yn': 'Y'
        },
        {
            'mdl_id': 'BAG_V1',
            'mdl_nm': 'Bagging 앙상블 모델 v1',
            'use_yn': 'N'
        },
        {
            'mdl_id': 'BAG_V2',
            'mdl_nm': 'Bagging 앙상블 모델 v2',
            'use_yn': 'N'
        },
        {
            'mdl_id': 'LR_V1',
            'mdl_nm': 'Logistic Regression v1',
            'use_yn': 'N'
        },
        {
            'mdl_id': 'LR_V2',
            'mdl_nm': 'Logistic Regression v2',
            'use_yn': 'N'
        },
        {
            'mdl_id': 'LR2_V1',
            'mdl_nm': 'Logistic Regression 2단계 v1',
            'use_yn': 'N'
        },
        {
            'mdl_id': 'LR3_V2',
            'mdl_nm': 'Logistic Regression 3단계 v2',
            'use_yn': 'N'
        },
        {
            'mdl_id': 'LGBM_V2',
            'mdl_nm': 'LightGBM 모델 v2 (2차 백업)',
            'use_yn': 'N'
        },
        # 2차 딥러닝 모델 (PyTorch 기반)
        {
            'mdl_id': 'KOBERT_2ND',
            'mdl_nm': 'KoBERT+LSTM+Attention 모델 (2차 주력)',
            'use_yn': 'Y'
        }
    ]
    
    # 모델 데이터 삽입
    for model_data in models_data:
        ModelRegistry.objects.get_or_create(
            mdl_id=model_data['mdl_id'],
            defaults={
                'mdl_nm': model_data['mdl_nm'],
                'use_yn': model_data['use_yn']
            }
        )

def reverse_populate_model_registry(apps, schema_editor):
    """롤백 시 추가한 모델들 삭제"""
    ModelRegistry = apps.get_model('woogawooga', 'ModelRegistry')
    
    model_ids = [
        'STACK_V1', 'STACK_V2', 'BAG_V1', 'BAG_V2',
        'LR_V1', 'LR_V2', 'LR2_V1', 'LR3_V2',
        'LGBM_V2', 'KOBERT_2ND'
    ]
    
    ModelRegistry.objects.filter(mdl_id__in=model_ids).delete()

class Migration(migrations.Migration):

    dependencies = [
        ('woogawooga', '0004_fix_inferenceresult_file_id_length'),
    ]

    operations = [
        migrations.RunPython(
            populate_model_registry,
            reverse_populate_model_registry,
        ),
    ]