"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 5.2.4.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
import os
from dotenv import load_dotenv

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# .env 파일 로드
load_dotenv(BASE_DIR / '.env')


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-0xu!p2i=p)a9y9e_f!=33yjq8&3*58pafgsv#c+kammhw)h%zu'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    "woogawooga.apps.WoogawoogaConfig",
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "channels",
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [BASE_DIR / "templates"],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.sqlite3',
#         'NAME': BASE_DIR / 'db.sqlite3',
#     }
# }

# 내 로컬디비
# DATABASES = {
#     "default": {
#         "ENGINE": "django.db.backends.mysql",
#         "NAME": "woogawooga",  # 데이터베이스이름
#         "USER": "root",  # root
#         "PASSWORD": "rhkr!77dlf8@",  # 비밀번호
#         "HOST": "127.0.0.1",  # 데이테베이스  호스트명  (동일  기기면 localhost)
#         "PORT": "3306",  # 데이터베이스  포트번호  (기본  3306)
#         "CHARSET": "utf8mb4",  # 4바이트  UTF-8
#     }
# }
DATABASES = {
    "default": {
        "ENGINE": os.getenv("DB_ENGINE"),
        "NAME": os.getenv("DB_NAME"),
        "USER": os.getenv("DB_USER"),
        "PASSWORD": os.getenv("DB_PASSWORD"),
        "HOST": os.getenv("DB_HOST"),
        "PORT": os.getenv("DB_PORT"),
        "OPTIONS": {
            "charset": os.getenv("DB_CHARSET"),
        },
    }
}
# 구글 클라우드 디비 설정
# import os
# from dotenv import load_dotenv

# load_dotenv()  # Codex에선 무시되고, 로컬에서만 동작

# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.mysql',
#         'NAME': os.getenv('DB_NAME'),
#         'USER': os.getenv('DB_USER'),
#         'PASSWORD': os.getenv('DB_PASSWORD'),
#         'HOST': os.getenv('DB_HOST'),
#         'PORT': os.getenv('DB_PORT'),
#         'OPTIONS': {
#             'init_command': "SET sql_mode='STRICT_TRANS_TABLES'",
#         }
#     }
# }


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'ko-kr'

TIME_ZONE = 'Asia/Seoul'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'
STATICFILES_DIRS = [BASE_DIR / "static"]

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# VITO API 설정
VITO_API_KEY = os.getenv('VITO_API_KEY')
VITO_API_URL = 'https://openapi.vito.ai/v1'

# OpenAI API 설정 (백업용)
OPENAI_API_KEY = os.getenv('OPENAI_API_KEY')
GPT_API_KEY = os.getenv('GPT_API_KEY')



# Channels 설정
ASGI_APPLICATION = 'config.asgi.application'

# Channel Layer 설정 (개발용 - In-Memory)
CHANNEL_LAYERS = {
    'default': {
        'BACKEND': 'channels.layers.InMemoryChannelLayer'
    }
}

# Channels 설정
ASGI_APPLICATION = "config.asgi.application"

# Channel Layer 설정 (개발용 - In-Memory)
CHANNEL_LAYERS = {"default": {"BACKEND": "channels.layers.InMemoryChannelLayer"}}

# 로깅 설정 - 터미널과 파일에 로그 출력을 위한 단순화된 설정
LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    "formatters": {
        "verbose": {
            "format": "[%(asctime)s] %(levelname)s [%(name)s:%(lineno)s] %(message)s",
            "datefmt": "%Y-%m-%d %H:%M:%S",
        },
    },
    "handlers": {
        "console": {
            "level": "INFO",
            "class": "logging.StreamHandler",
            "formatter": "verbose",
        },
        "file": {
            "level": "DEBUG",
            "class": "logging.FileHandler",
            "filename": BASE_DIR / "logs" / "woogawooga.log",
            "formatter": "verbose",
            "encoding": "utf-8",
        },
    },
    # 모든 로거의 최상위인 root 로거를 설정합니다.
    # 이렇게 하면 Django와 woogawooga 앱을 포함한 모든 로그가 이 설정을 따릅니다.
    "root": {
        "handlers": ["console", "file"],
        "level": "INFO",
    },
    # 특정 앱의 로그 레벨만 조정하고 싶을 때 아래처럼 추가할 수 있습니다.
    "loggers": {
        "django": {
            # django 관련 로그가 너무 많이 보인다면 레벨을 'WARNING'으로 조정하세요.
            "level": "INFO",
            "handlers": ["console", "file"],
            "propagate": False,  # root 로거로 전파하지 않아 중복 출력을 막습니다.
        },
    },
}


# 로깅 설정 - 터미널에 실시간 로그 출력을 위한 설정
# LOGGING = {
#     "version": 1,
#     "disable_existing_loggers": False,
#     "formatters": {
#         "verbose": {
#             "format": "[%(asctime)s] %(levelname)s [%(name)s:%(lineno)s] %(message)s",
#             "datefmt": "%Y-%m-%d %H:%M:%S",
#         },
#         "simple": {
#             "format": "[%(levelname)s] %(message)s",
#         },
#     },
#     "handlers": {
#         "console": {
#             "level": "INFO",  # 개발 중에는 'DEBUG'로 설정하여 더 상세한 정보 확인 가능
#             "class": "logging.StreamHandler",
#             "formatter": "verbose",
#             "stream": "ext://sys.stdout",  # UTF-8 인코딩을 위한 설정
#         },
#         "file": {
#             "level": "DEBUG",
#             "class": "logging.FileHandler",
#             "filename": BASE_DIR / "logs" / "woogawooga.log",
#             "formatter": "verbose",
#             "encoding": "utf-8",  # UTF-8 인코딩 명시적 설정
#         },
#     },
#     "loggers": {
#         "django": {
#             "handlers": ["console"],
#             "level": "INFO",
#             "propagate": False,
#         },
#         "woogawooga": {  # 우리 앱을 위한 로거
#             "handlers": ["console", "file"],
#             "level": "INFO",
#             "propagate": True,  # 하위 로거들이 상위로 전파되도록 설정
#         },
#         "woogawooga.views": {  # views 모듈 전용 로거
#             "handlers": ["console", "file"],
#             "level": "INFO",
#             "propagate": False,
#         },
#         "": {  # 루트 로거 - 모든 로그를 캐치
#             "handlers": ["console"],
#             "level": "INFO",
#         },
#     },
# }
